name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: patkaczm/esphomeassistant:0.0.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Run tests
        run: |
          ctest --test-dir build

